### PR TITLE
Launch Promptconf.com

### PR DESCRIPTION
**Pull request by arelia**
**Preview: https://prompt-conf-dev.netlify.com/**

## To Do
_should complete bold items to launch; could launch without non-bold things, e.g. sponsors could sign up for notifications if we don't yet have a sponsorship process_
- [x] **Get headshots, confirm titles with keynoters (link to their social media?)**
- [x] **add code of conduct**
- [x] **remove any links to 404** (placeholders for forms etc.)
- [x] Remove MailChimp interest groups we don't need (i.e. we don't need a speaker group if CFP is open)
- [x] add sponsorship prospectus (and link to inquiry form?)
- [x] add talk submission form
- [x] After merging, see [`Conference Launch`](https://github.com/promptconf/promptconf.github.io/milestone/5) milestone issues

### Before launch we should
- [x] 👍 from Naomi
- [ ] 👍 from Mark
- [x] 👍 from ActiveCampaign

## Organizers should
- Review copy - is there content we need to add or fix?
  - left out the phrase "joy of computing" so that we don't look affiliated with other conferences
  - On the list of CFP prompts, I'm adding something front-endy. Point out any other areas where we can be more tech-area-agnostic
- Check that links work and flow through the site makes sense

### CODE REVIEW

**Comment by chelseatroy** [comment]
Hi! One really quick thing: I left my job at Ascent. I now work for Zooniverse and the University of Chicago—no ascent :)

**Comment by arelia** [comment]
@chelseatroy fixed!

**Comment by chelseatroy** [comment]
Hi! Here is the CFP Form:

https://docs.google.com/forms/d/1COPJVqgjU5m1flzbFgYkj9XvHtEQ8TEGLEep8OuKJis/edit?usp=sharing

Currently anyone with the link can edit it. We'll shut that down before we publish :) 

Name and email fields are on this form, but I'm not going to look at them. Instead I'll add @loooorenanicole as a collaborator and she can scrub that before we see the proposals.

**Comment by chelseatroy** [comment]
Draft CoC:

https://docs.google.com/document/d/10A3waqNAV-GIRnodjgS6uhA5f0RqF9y95hKTiI2_ww4/edit?usp=sharing

**Review by sunahsuh — APPROVED** [review]
@arelia YOU'RE AMAAAAZING

Unless anyone else has objections, let's 1. change the CFP closing date (6/30?) and 2. close that form to edits, heh, and let's publish and start getting the word out. If Mark has changes he'd like to see to the site we can make those edits when we hear back from him, but we do need to open the CFP now if we want to stay on schedule.

**Pull request merged**
